#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMFormFieldDefinition.h"
#import "CMOcrPhotoTextElement.h"
@protocol CMFormFieldDefinition;
@class CMFormFieldDefinition;
@protocol CMOcrPhotoTextElement;
@class CMOcrPhotoTextElement;



@protocol CMFieldResult
@end

@interface CMFieldResult : CMObject

/* Target field to extract from the form [optional]
 */
@property(nonatomic) CMFormFieldDefinition* targetField;
/* Result field value(s) extracted [optional]
 */
@property(nonatomic) NSArray<CMOcrPhotoTextElement>* fieldValues;

@end
