#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMFieldResult.h"
#import "CMTableResult.h"
@protocol CMFieldResult;
@class CMFieldResult;
@protocol CMTableResult;
@class CMTableResult;



@protocol CMFormRecognitionResult
@end

@interface CMFormRecognitionResult : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Result of form field OCR data extraction [optional]
 */
@property(nonatomic) NSArray<CMFieldResult>* fieldValueExtractionResult;
/* Result of form table OCR data extraction [optional]
 */
@property(nonatomic) NSArray<CMTableResult>* tableValueExtractionResults;
/* Diagnostic images - default is null, enable diagnostics=true to populate this parameter with one image per field [optional]
 */
@property(nonatomic) NSArray<NSString*>* diagnostics;
/* Optional; populated when using photo/recognize/form/advanced with the Setting Name of the best-matching highest-relevance form [optional]
 */
@property(nonatomic) NSString* bestMatchFormSettingName;

@end
