#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFormTableColumnDefinition
@end

@interface CMFormTableColumnDefinition : CMObject

/* The identifier of the field; use this to identify which field is being referenced [optional]
 */
@property(nonatomic) NSString* columnID;
/* Optional - the top anchor of the column heading [optional]
 */
@property(nonatomic) NSString* topAnchor;
/* Optional - the matching mode for the anchor.  Possible values are Complete (requires the entire anchor to match) and Partial (allows only part of the anchor to match).  Default is Partial. [optional]
 */
@property(nonatomic) NSString* anchorMode;
/* The data type of the field; possible values are INTEGER (Integer value), STRING (Arbitrary string value, spaces are permitted), DATE (Date in a structured format), DECIMAL (Decimal number), ALPHANUMERIC (Continuous alphanumeric string with no spaces), STRINGNOWHITESPACE (A string that contains no whitespace characters), SERIALNUMBER (A serial-number style string that contains letters and numbers, and certain symbols; must contain at least one number), ALPHAONLY (Alphabet characters only, no numbers or symbols or whitespace) [optional]
 */
@property(nonatomic) NSString* dataType;
/* Optional - the target number of digits in the field; useful for fixed-length fields [optional]
 */
@property(nonatomic) NSNumber* minimumCharacterCount;
/* Optional - set to false to block values that contain numeric digits, set to true to allow numeric digits [optional]
 */
@property(nonatomic) NSNumber* allowNumericDigits;

@end
