#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMFormFieldDefinition.h"
#import "CMFormTableDefinition.h"
@protocol CMFormFieldDefinition;
@class CMFormFieldDefinition;
@protocol CMFormTableDefinition;
@class CMFormTableDefinition;



@protocol CMFormDefinitionTemplate
@end

@interface CMFormDefinitionTemplate : CMObject

/* Field definitions in the template; a field is comprised of a key/value pair [optional]
 */
@property(nonatomic) NSArray<CMFormFieldDefinition>* fieldDefinitions;
/* Table definitions in the template; a table is comprised of columns and rows and exists in a 2-dimensional layout; a common example of a table would be an invoice [optional]
 */
@property(nonatomic) NSArray<CMFormTableDefinition>* tableDefinitions;

@end
