#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMOcrWordElement
@end

@interface CMOcrWordElement : CMObject

/* Text of the word [optional]
 */
@property(nonatomic) NSString* wordText;
/* Line number of the word [optional]
 */
@property(nonatomic) NSNumber* lineNumber;
/* Index of the word in the line [optional]
 */
@property(nonatomic) NSNumber* wordNumber;
/* X location of the left edge of the word in pixels [optional]
 */
@property(nonatomic) NSNumber* xLeft;
/* Y location of the top edge of the word in pixels [optional]
 */
@property(nonatomic) NSNumber* yTop;
/* Width of the word in pixels [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height of the word in pixels [optional]
 */
@property(nonatomic) NSNumber* height;
/* Confidence level of the machine learning result; possible values are 0.0 (lowest accuracy) - 1.0 (highest accuracy) [optional]
 */
@property(nonatomic) NSNumber* confidenceLevel;
/* Index of the containing block [optional]
 */
@property(nonatomic) NSNumber* blockNumber;
/* Index of the containing paragraph [optional]
 */
@property(nonatomic) NSNumber* paragraphNumber;
/* Index of the containing page [optional]
 */
@property(nonatomic) NSNumber* pageNumber;

@end
