#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMPoint.h"
@protocol CMPoint;
@class CMPoint;



@protocol CMOcrPhotoTextElement
@end

@interface CMOcrPhotoTextElement : CMObject

/* Text of the word [optional]
 */
@property(nonatomic) NSString* text;
/* X location of the left edge of the word in pixels [optional]
 */
@property(nonatomic) NSNumber* xLeft;
/* Y location of the top edge of the word in pixels [optional]
 */
@property(nonatomic) NSNumber* yTop;
/* Width of the word in pixels [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height of the word in pixels [optional]
 */
@property(nonatomic) NSNumber* height;
/* Points that form the bounding polygon around the text [optional]
 */
@property(nonatomic) NSArray<CMPoint>* boundingPoints;
/* Confidence level of the machine learning result; possible values are 0.0 (lowest accuracy) - 1.0 (highest accuracy) [optional]
 */
@property(nonatomic) NSNumber* confidenceLevel;

@end
