#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMOcrWordElement.h"
@protocol CMOcrWordElement;
@class CMOcrWordElement;



@protocol CMOcrPageResultWithWordsWithLocation
@end

@interface CMOcrPageResultWithWordsWithLocation : CMObject


@property(nonatomic) NSNumber* successful;
/* Page number of the page that was OCR-ed, starting with 1 for the first page in the PDF file [optional]
 */
@property(nonatomic) NSNumber* pageNumber;
/* Word elements in the image [optional]
 */
@property(nonatomic) NSArray<CMOcrWordElement>* words;

@end
