#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMOcrPageResultWithWordsWithLocation.h"
@protocol CMOcrPageResultWithWordsWithLocation;
@class CMOcrPageResultWithWordsWithLocation;



@protocol CMPdfToWordsWithLocationResult
@end

@interface CMPdfToWordsWithLocationResult : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* OCR page results [optional]
 */
@property(nonatomic) NSArray<CMOcrPageResultWithWordsWithLocation>* ocrPages;

@end
