#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMOcrPageResult.h"
@protocol CMOcrPageResult;
@class CMOcrPageResult;



@protocol CMPdfToTextResponse
@end

@interface CMPdfToTextResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Page OCR results [optional]
 */
@property(nonatomic) NSArray<CMOcrPageResult>* ocrPages;

@end
