#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMOcrPhotoTextElement.h"
@protocol CMOcrPhotoTextElement;
@class CMOcrPhotoTextElement;



@protocol CMPhotoToWordsWithLocationResult
@end

@interface CMPhotoToWordsWithLocationResult : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Word elements in the image [optional]
 */
@property(nonatomic) NSArray<CMOcrPhotoTextElement>* textElements;
/* Typically null.  To analyze OCR performance, enable diagnostic mode by adding the HTTP header \"DiagnosticMode\" with the value \"true\".  When this is true, a diagnostic image showing the details of the OCR result will be set in PNG format into DiagnosticImage. [optional]
 */
@property(nonatomic) NSData* diagnosticImage;

@end
