#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMPoint
@end

@interface CMPoint : CMObject

/* X location in 2D in the image, where 0 represents the left edge of the image [optional]
 */
@property(nonatomic) NSNumber* X;
/* Y location in 2D in the image, where 0 represents the top edge of the image [optional]
 */
@property(nonatomic) NSNumber* Y;

@end
