#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMReceiptRecognitionResult
@end

@interface CMReceiptRecognitionResult : CMObject


@property(nonatomic) NSNumber* successful;

@property(nonatomic) NSDate* timestamp;

@property(nonatomic) NSString* businessName;

@property(nonatomic) NSString* addressString;

@property(nonatomic) NSString* phoneNumber;

@property(nonatomic) NSNumber* receiptTotal;

@end
