#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMFormTableDefinition.h"
#import "CMTableRowResult.h"
@protocol CMFormTableDefinition;
@class CMFormTableDefinition;
@protocol CMTableRowResult;
@class CMTableRowResult;



@protocol CMTableResult
@end

@interface CMTableResult : CMObject

/* The input table definition for reference [optional]
 */
@property(nonatomic) CMFormTableDefinition* tableDefinition;
/* Rows of data in the table [optional]
 */
@property(nonatomic) NSArray<CMTableRowResult>* tableRowsResult;

@end
