#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMOcrPhotoTextElement.h"
@protocol CMOcrPhotoTextElement;
@class CMOcrPhotoTextElement;



@protocol CMTableCellResult
@end

@interface CMTableCellResult : CMObject

/* The ID of the column [optional]
 */
@property(nonatomic) NSString* columnID;
/* Result cell value(s) extracted [optional]
 */
@property(nonatomic) NSArray<CMOcrPhotoTextElement>* cellValues;

@end
