#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMPreprocessingApi: NSObject <CMApi>

extern NSString* kCMPreprocessingApiErrorDomain;
extern NSInteger kCMPreprocessingApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Detect and unrotate a document image
/// Detect and unrotate an image of a document (e.g. that was scanned at an angle).  Great for document scanning applications; once unskewed, this image is perfect for converting to PDF using the Convert API or optical character recognition using the OCR API.
///
/// @param imageFile Image file to perform OCR on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) preprocessingUnrotateWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Detect and unskew a photo of a document
/// Detect and unskew a photo of a document (e.g. taken on a cell phone) into a perfectly square image.  Great for document scanning applications; once unskewed, this image is perfect for converting to PDF using the Convert API or optical character recognition using the OCR API.
///
/// @param imageFile Image file to perform OCR on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) preprocessingUnskewWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;



@end
