#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* ocrapi
* The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMReceiptsApi: NSObject <CMApi>

extern NSString* kCMReceiptsApiErrorDomain;
extern NSInteger kCMReceiptsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Convert a photo of a receipt into a CSV file containing structured information from the receipt
/// Leverage Deep Learning to automatically turn a photo of a receipt into a CSV file containing the structured information from the receipt.
///
/// @param imageFile Image file to perform OCR on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) receiptsPhotoToCSVWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;



@end
